# Generated by Django 4.0.3 on 2022-03-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gt_user', '0002_user_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
